services:
  postgres:
    build:
      context: .
      dockerfile: postgres.dockerfile
    image: 'web-scraper-db'
    container_name: '${PG_CONTAINER_NAME}'
    environment:
      POSTGRES_DB: '${POSTGRES_DB}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      PGDATA: ${PGDATA}
    volumes:
      - dbtuto:/data/web-scraper-data

    ports:
      - '5432:5432'
    restart: unless-stopped

volumes:
  dbtuto:
    external: true