auction_site = {
	'source': 'https://nedradv.ru/nedradv/ru/auction',
	'table': '.g-color-black-opacity-0_6',
	'row': 'tr',
	'link': 'a',
	'object': '/html/body/main/section[3]/div/div[1]/div[1]',
	'date': './/div[1]/h1',
	'square': ['.//div[1]/p', './/div[1]/h1/i[1]'],
	'region': './/div[1]/h1',
	'status': './/dl[1]/dd',
	'submit_deadline': './/dl[8]',
	'contribution': './/dl[4]',
	'organizer': './/dl[6]',
	'next_page': '.u-pagination-v1-4--active',
	'months': ['января', 'февраля', 'марта', 'апреля', 'мая', 'июня', 'июля', 'августа', 'сентября', 'октября', 'ноября', 'декабря'],
}